### ISSUE TITLE
Utilize data loading

### ISSUE THREAD

**Issue by Kaito0506** [minhify/CTU-CSIROBoeingPhase5#1]
Currently, the satellite data is storage on cloud server. It require us to download and process data to create dataset every time. It consume a large amount of time. Write a module  to download and store dataset for several uses in the future

**Comment by hongan2510** [comment]
could please assign me to this issue #1

**Comment by Kaito0506** [comment]
@hongan2510 of course, here you are

**Comment by hongan2510** [comment]
hi @Kaito0506, I m done, please tell me it works properly

**Comment by Kaito0506** [comment]
@hongan2510, you are great. it worked

**Comment by Kaito0506** [comment]
solved #1
